### PR TITLE
style: add .editorconfig file to support uniform editor/IDE settings

### PR DESCRIPTION
**Pull request by intelfisz**

### CODE REVIEW

**Comment by artek-koltun** [comment]
Do we have a github action to check if a pr is compliant with these rules?

**Comment by intelfisz** [comment]
> Do we have a github action to check if a pr is compliant with these rules?

I don't think there is a linter for that or that we need one. It just facilitates some rules enforcement which are already checked by some of our linters - e.g. trailing newline in md files or tab-based formatting with go fmt. For people using supported editors it will facilitate proper configuration. It will not let my editor forget the newline which would make the md-linter fail. It is popular with many GH projects.

**Comment by artek-koltun** [comment]
> I don't think there is a linter for that or that we need one. It just facilitates some rules enforcement which are already checked by some of our linters - e.g. trailing newline in md files or tab-based formatting with go fmt. For people using supported editors it will facilitate proper configuration. It will not let my editor forget the newline which would make the md-linter fail. It is popular with many GH projects.

I am thinking if we do not force people to adhere to all the rules, then they do not make sense... If only some of them are checked, then it means we do not adhere to the rules. If someone uses a simple notepad adding something not-complaint, we should worn in CI. Think [this](https://github.com/marketplace/actions/editorconfig-action) github action should do the job

**Comment by intelfisz** [comment]
> > I don't think there is a linter for that or that we need one. It just facilitates some rules enforcement which are already checked by some of our linters - e.g. trailing newline in md files or tab-based formatting with go fmt. For people using supported editors it will facilitate proper configuration. It will not let my editor forget the newline which would make the md-linter fail. It is popular with many GH projects.
> 
> I am thinking if we do not force people to adhere to all the rules, then they do not make sense... If only some of them are checked, then it means we do not adhere to the rules. If someone uses a simple notepad adding something not-complaint, we should worn in CI. Think [this](https://github.com/marketplace/actions/editorconfig-action) github action should do the job

Sounds good! Especially since there is a ready-to-use linter. I am for it then.

**Review by artek-koltun — CHANGES_REQUESTED** [review]
Github Action should be added

**Comment by artek-koltun** [comment]
> > Github Action should be added
> 
> Added.

Could I ask you to temporarily add a wrong indentation or whatever to make sure that it can really detect that issue?

**Comment by intelfisz** [comment]
> > > Github Action should be added
> > 
> > 
> > Added.
> 
> Could I ask you to temporarily add a wrong indentation or whatever to make sure that it can really detect that issue?

It does - this is why I added the LICENSE exception to .editorconfig - it detected that it uses spaces there which was violating the rule in .editorconfig.

**Review by artek-koltun — APPROVED** [review]

**Pull request merged**
